name: Snyk Code Analysis Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-code-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Run Snyk Code Analysis
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        ORG_ID: dd5850c3-5d7a-4966-89b3-e24ec510f9fc
      run: |
        cat > snyk_code_scan.py << 'EOF'
[Previous Python script content remains the same...]
